<?php
// enable_claude_haiku.php
// Habilita la integración "Claude Haiku 4.5" para todos los clientes (escribe un flag en inc/)

require_once __DIR__ . '/inc/bootstrap.php';

$title = 'Habilitar Claude Haiku 4.5';

require_login();

$cu = current_user();

$tipoGlobal = isset($_SESSION['tipo_global'])
    ? $_SESSION['tipo_global']
    : (isset($cu['tipo_global']) ? $cu['tipo_global'] : '');

$rol = isset($_SESSION['rol'])
    ? $_SESSION['rol']
    : (isset($cu['rol']) ? $cu['rol'] : '');

if (!in_array($tipoGlobal, array('admin_evento', 'super_admin', 'superadmin'), true)
    && $rol !== 'admin') {
    http_response_code(403);
    include __DIR__ . '/inc/layout_top.php';
    ?>
    <div class="card" style="max-width:640px;margin:32px auto;">
      <h2>Acceso restringido</h2>
      <p>Esta acción es solo para administradores.</p>
      <p style="margin-top:8px;"><a href="panel_admin.php" class="btn">Volver</a></p>
    </div>
    <?php
    include __DIR__ . '/inc/layout_bottom.php';
    exit;
}

// POST confirma la acción
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (!isset($_POST['confirm']) || $_POST['confirm'] !== 'yes') {
        header('Location: panel_admin.php');
        exit;
    }

    $flagDir = __DIR__ . '/inc';
    if (!is_dir($flagDir) || !is_writable($flagDir)) {
        include __DIR__ . '/inc/layout_top.php';
        ?>
        <div class="card" style="max-width:640px;margin:32px auto;">
          <h2>Error</h2>
          <p>No se puede escribir en el directorio de configuración.</p>
          <p><a href="panel_admin.php" class="btn">Volver</a></p>
        </div>
        <?php
        include __DIR__ . '/inc/layout_bottom.php';
        exit;
    }

    $flagFile = $flagDir . '/feature_claude_haiku.php';
    $content = "<?php\n// Generated by enable_claude_haiku.php on " . date('c') . "\n\$CLAUDE_HAIKU_ENABLED = true;\nreturn true;\n";

    $ok = @file_put_contents($flagFile, $content, LOCK_EX);
    if ($ok === false) {
        include __DIR__ . '/inc/layout_top.php';
        ?>
        <div class="card" style="max-width:640px;margin:32px auto;">
          <h2>Error</h2>
          <p>No se pudo crear el archivo de flag. Revisa permisos.</p>
          <p><a href="panel_admin.php" class="btn">Volver</a></p>
        </div>
        <?php
        include __DIR__ . '/inc/layout_bottom.php';
        exit;
    }

    header('Location: panel_admin.php?msg=claude_enabled');
    exit;
}

include __DIR__ . '/inc/layout_top.php';
?>

<div class="card" style="max-width:640px;margin:32px auto;">
  <h1 style="margin:0;">Habilitar Claude Haiku 4.5</h1>
  <p style="color:var(--muted);margin-top:6px;">Esta acción habilitará Claude Haiku 4.5 para todos los clientes del sistema. Esta operación afecta a todos los sitios y no es reversible desde aquí (podés borrar manualmente el archivo de flag para deshabilitar).</p>
  <form method="post" style="margin-top:12px;">
    <input type="hidden" name="confirm" value="yes">
    <button class="btn" type="submit">Confirmar y habilitar</button>
    <a href="panel_admin.php" class="btn secondary" style="margin-left:8px;">Cancelar</a>
  </form>
</div>

<?php include __DIR__ . '/inc/layout_bottom.php'; ?>
