<?php
require_once __DIR__ . '/inc/bootstrap.php';
require_once __DIR__ . '/inc/arca.php';
require_once __DIR__ . '/inc/billing_financials.php';
$title = 'Facturación';
require_login();
$pdo = db(); $cu = current_user();
$adminId = isset($cu['id']) ? (int)$cu['id'] : 0;
$role = isset($cu['tipo_global']) ? (string)$cu['tipo_global'] : '';
$isSuper = in_array($role, array('super_admin','superadmin'), true);
if ($adminId <= 0 || ($role !== 'admin_evento' && !$isSuper)) abort_404('No tenes permiso.');
$filters = array('event_id'=>isset($_GET['event_id'])?(int)$_GET['event_id']:0,'provider'=>isset($_GET['provider'])?(string)$_GET['provider']:'','status'=>isset($_GET['status'])?(string)$_GET['status']:'','date_from'=>isset($_GET['date_from'])?(string)$_GET['date_from']:'','date_to'=>isset($_GET['date_to'])?(string)$_GET['date_to']:'');
$events = tickex_billing_events($pdo, $adminId, $isSuper);
$allowedEventIds = array(); foreach ($events as $eventRow) $allowedEventIds[(int)$eventRow['id']] = true;
if ($filters['event_id'] > 0 && !isset($allowedEventIds[$filters['event_id']])) $filters['event_id'] = 0;
$report = tickex_billing_report($pdo, $adminId, $isSuper, $filters); $summary = $report['summary'];
$arcaConfig = arca_get_config();
$arcaConfigured = is_array($arcaConfig) && !empty($arcaConfig['cuit']) && !empty($arcaConfig['cert']) && !empty($arcaConfig['key']);
$arcaMode = $arcaConfigured && isset($arcaConfig['modo']) && $arcaConfig['modo'] === 'produccion' ? 'Producción' : 'Homologación';
include __DIR__ . '/inc/layout_top.php';
include __DIR__ . '/inc/facturacion_admin_view.php';
include __DIR__ . '/inc/layout_bottom.php';
