<?php
require_once __DIR__.'/inc/bootstrap.php';
require_once __DIR__.'/inc/subscriptions.php';
require_login();$pdo=db();$cu=current_user();$adminId=tickex_admin_id($cu);if(!tickex_is_super_admin($cu))abort_404('No tenés permiso.');
tickex_subscriptions_ensure_schema($pdo);$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!tickex_csrf_verify(isset($_POST['_csrf'])?(string)$_POST['_csrf']:''))$error='La sesión venció. Actualizá la página.';
 else try{$action=isset($_POST['action'])?(string)$_POST['action']:'';
  if($action==='settings'){tickex_subscription_set_enforcement($pdo,!empty($_POST['enforcement_enabled']),$adminId);flash('ok','Modo de suscripciones actualizado.');}
  elseif($action==='plan'){tickex_subscription_save_plan($pdo,$_POST);flash('ok','Plan guardado.');}
  elseif($action==='assign'){tickex_subscription_assign($pdo,(int)$_POST['organizer_id'],(int)$_POST['plan_id'],(string)$_POST['subscription_status'],trim((string)$_POST['ends_at']),isset($_POST['note'])?$_POST['note']:'',$adminId,!empty($_POST['limit_exempt']));flash('ok','Suscripción del organizador actualizada.');}
  header('Location: superadmin_suscripciones.php'.(!empty($_GET['q'])?'?q='.urlencode($_GET['q']):''));exit;
 }catch(Exception $e){$error=$e->getMessage();}
}
$q=isset($_GET['q'])?trim((string)$_GET['q']):'';$settings=tickex_subscription_settings($pdo);$plans=tickex_subscription_plans($pdo,true);$organizers=tickex_subscription_admin_rows($pdo,$q);$changes=tickex_subscription_recent_changes($pdo,20);$statuses=tickex_subscription_statuses();$csrf=tickex_csrf_token();$flashes=flash_get_all();$title='Planes y suscripciones';include __DIR__.'/inc/layout_top.php';
?>
<style>
.plans-page{max-width:1200px;margin:0 auto;display:grid;gap:16px}.plans-hero{padding:29px;background:radial-gradient(circle at 90% 0,rgba(68,215,238,.16),transparent 28%),linear-gradient(135deg,#171b38,#35226e)}.plans-kicker{color:#5edbef;text-transform:uppercase;letter-spacing:.13em;font-size:11px;font-weight:900}.plans-hero h1{font-size:clamp(32px,5vw,48px);letter-spacing:-.04em;margin:6px 0}.plans-hero p{color:#c5c8d8;margin:0}.plans-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;flex-wrap:wrap}.plans-head h2{margin:4px 0}.plans-mode{padding:13px 16px;border-radius:14px;border:1px solid var(--line);background:rgba(255,255,255,.025)}.plans-mode strong{display:block}.plans-mode small{color:var(--muted)}.plans-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:11px}.plan-card{padding:17px;border:1px solid var(--line);border-radius:15px;background:rgba(255,255,255,.02)}.plan-card h3{font-size:24px;margin:5px 0}.plan-badge{display:inline-block;padding:4px 8px;border:1px solid var(--line);border-radius:999px;font-size:10px;text-transform:uppercase}.plan-card details{margin-top:14px}.plan-form{display:grid;gap:9px;margin-top:12px}.plan-form-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.plan-form textarea{min-height:90px}.plans-search{display:flex;gap:9px}.plans-search input{flex:1}.subscriber-list{display:grid;gap:9px;margin-top:15px}.subscriber{display:grid;grid-template-columns:minmax(190px,1.2fr) minmax(140px,.7fr) minmax(150px,.8fr) minmax(130px,.6fr) auto;gap:10px;align-items:end;padding:14px;border:1px solid var(--line);border-radius:14px}.subscriber-name strong,.subscriber-name small{display:block}.subscriber-name small{color:var(--muted);overflow:hidden;text-overflow:ellipsis}.subscriber label{font-size:11px;color:var(--muted)}.subscriber label select,.subscriber label input{margin-top:4px}.usage strong{display:block}.usage small{color:var(--muted)}@media(max-width:950px){.plans-grid{grid-template-columns:1fr}.subscriber{grid-template-columns:1fr 1fr}.subscriber-name{grid-column:1/-1}}@media(max-width:560px){.subscriber,.plan-form-grid{grid-template-columns:1fr}.plans-search{display:grid}}
</style>
<main class="plans-page"><section class="card plans-hero"><div class="plans-kicker">Modelo comercial</div><h1>Planes y suscripciones</h1><p>Editá la oferta, asigná cada organizador y controlá el consumo real de QR.</p></section>
<?php foreach($flashes as $f):?><div class="flash <?php echo e($f['type']);?>"><?php echo e($f['msg']);?></div><?php endforeach;?><?php if($error!==''):?><div class="flash err"><?php echo e($error);?></div><?php endif;?>
<section class="card"><div class="plans-head"><div><div class="plans-kicker">Aplicación de reglas</div><h2>Modo de suscripciones</h2></div><form method="post" class="plans-mode"><input type="hidden" name="_csrf" value="<?php echo e($csrf);?>"><input type="hidden" name="action" value="settings"><label><input type="checkbox" name="enforcement_enabled" value="1"<?php echo !empty($settings['enforcement_enabled'])?' checked':'';?>> Aplicar comisión y límites de los planes</label><small><?php echo empty($settings['enforcement_enabled'])?'Ahora solo medimos: ninguna venta será bloqueada.':'Las reglas están activas para los organizadores.';?></small><button class="btn secondary" type="submit">Guardar modo</button></form></div></section>
<section class="card"><div class="plans-head"><div><div class="plans-kicker">Catálogo editable</div><h2>Planes</h2></div></div><div class="plans-grid"><?php foreach($plans as $plan):$features=json_decode((string)$plan['features_json'],true);if(!is_array($features))$features=array();?><article class="plan-card"><span class="plan-badge"><?php echo $plan['status']==='active'?'Publicado':'Borrador';?></span><h3><?php echo e($plan['name']);?></h3><p class="muted"><?php echo e($plan['description']);?></p><strong><?php echo e(number_format((float)$plan['service_fee_percent'],2,',','.'));?>% por venta</strong><p class="muted"><?php echo $plan['qr_limit_monthly']===null?'QR sin límite definido':e(number_format((int)$plan['qr_limit_monthly'],0,',','.')).' QR por mes';?> · <?php echo $plan['monthly_price']===null?'Precio a definir':'$'.e(number_format((float)$plan['monthly_price'],0,',','.')).'/mes';?></p><details><summary>Editar plan</summary><form method="post" class="plan-form"><input type="hidden" name="_csrf" value="<?php echo e($csrf);?>"><input type="hidden" name="action" value="plan"><input type="hidden" name="id" value="<?php echo (int)$plan['id'];?>"><div class="plan-form-grid"><label>Nombre<input name="name" value="<?php echo e($plan['name']);?>" required></label><label>Código<input name="code" value="<?php echo e($plan['code']);?>" required></label><label>Precio mensual<input type="number" min="0" step="0.01" name="monthly_price" value="<?php echo e($plan['monthly_price']);?>" placeholder="A definir"></label><label>Costo de servicio %<input type="number" min="0" max="100" step="0.01" name="service_fee_percent" value="<?php echo e($plan['service_fee_percent']);?>" required></label><label>Límite QR mensual<input type="number" min="0" name="qr_limit_monthly" value="<?php echo e($plan['qr_limit_monthly']);?>" placeholder="Sin límite"></label><label>Orden<input type="number" name="sort_order" value="<?php echo (int)$plan['sort_order'];?>"></label></div><label>Descripción<textarea name="description"><?php echo e($plan['description']);?></textarea></label><label>Beneficios, uno por línea<textarea name="features"><?php echo e(implode("\n",$features));?></textarea></label><label>Estado<select name="status"><option value="active"<?php echo $plan['status']==='active'?' selected':'';?>>Publicado</option><option value="draft"<?php echo $plan['status']==='draft'?' selected':'';?>>Borrador</option></select></label><button class="btn" type="submit">Guardar plan</button></form></details></article><?php endforeach;?></div></section>
<section class="card"><div class="plans-head"><div><div class="plans-kicker">Organizadores</div><h2>Suscriptores</h2></div><form class="plans-search" method="get"><input name="q" value="<?php echo e($q);?>" placeholder="Buscar nombre o email"><button class="btn" type="submit">Buscar</button></form></div><div class="subscriber-list"><?php foreach($organizers as $org):?><form method="post" class="subscriber"><input type="hidden" name="_csrf" value="<?php echo e($csrf);?>"><input type="hidden" name="action" value="assign"><input type="hidden" name="organizer_id" value="<?php echo (int)$org['id'];?>"><div class="subscriber-name"><strong><?php echo e(trim($org['nombre'].' '.$org['apellido'])?:$org['email']);?></strong><small><?php echo e($org['email']);?></small><label><input type="checkbox" name="limit_exempt" value="1"<?php echo !empty($org['limit_exempt'])?' checked':'';?>> Sin límite de QR</label></div><label>Plan<select name="plan_id"><?php foreach($plans as $plan):?><option value="<?php echo (int)$plan['id'];?>"<?php echo (int)$org['plan_id']===(int)$plan['id']?' selected':'';?>><?php echo e($plan['name']);?><?php echo $plan['status']==='draft'?' · borrador':'';?></option><?php endforeach;?></select></label><label>Estado<select name="subscription_status"><?php foreach($statuses as $key=>$label):?><option value="<?php echo e($key);?>"<?php echo $org['subscription_status']===$key?' selected':'';?>><?php echo e($label);?></option><?php endforeach;?></select></label><label>Vigente hasta<input type="date" name="ends_at" value="<?php echo e($org['ends_at']?substr($org['ends_at'],0,10):'');?>"></label><div class="usage"><strong><?php echo (int)$org['used'];?> QR</strong><small>este mes<?php echo !empty($org['limit_exempt'])?' · sin límite':($org['qr_limit_monthly']!==null?' de '.(int)$org['qr_limit_monthly']:'');?></small><input type="hidden" name="note" value="Actualización desde el panel"></div><button class="btn secondary" type="submit">Actualizar</button></form><?php endforeach;?></div></section></main><?php include __DIR__.'/inc/layout_bottom.php';?>
