<?php
require_once __DIR__ . '/inc/bootstrap.php';
require_once __DIR__ . '/inc/support_center.php';
require_once __DIR__ . '/inc/notificaciones.php';
require_login();
$pdo=db(); $cu=current_user(); $adminId=tickex_admin_id($cu);
if (!tickex_is_super_admin($cu)) abort_404('No tenés permiso.');
tickex_support_ensure_schema($pdo);
$categories=tickex_support_categories(); $statuses=tickex_support_statuses(); $priorities=tickex_support_priorities(); $error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!tickex_csrf_verify(isset($_POST['_csrf'])?(string)$_POST['_csrf']:''))$error='La sesión venció. Actualizá la página.';
 else{
  $action=isset($_POST['action'])?(string)$_POST['action']:''; $ticketId=isset($_POST['ticket_id'])?(int)$_POST['ticket_id']:0;
  if($action==='reply'){
   list($ok,$message)=tickex_support_add_message($pdo,$ticketId,$adminId,true,isset($_POST['body'])?$_POST['body']:'');
   if($ok){$target=tickex_support_get_ticket($pdo,$ticketId,$adminId,true);if($target)add_notification((int)$target['admin_id'],'Tickex respondió tu consulta '.$target['public_id'].'.','support',array('url'=>'soporte.php?id='.$ticketId),$pdo);flash('ok',$message);header('Location: superadmin_soporte.php?id='.$ticketId);exit;} $error=$message;
  }elseif($action==='update'){
   list($ok,$message)=tickex_support_update_ticket($pdo,$ticketId,$adminId,true,isset($_POST['status'])?$_POST['status']:'',isset($_POST['priority'])?$_POST['priority']:'');
   if($ok){$target=tickex_support_get_ticket($pdo,$ticketId,$adminId,true);if($target)add_notification((int)$target['admin_id'],'Tu consulta '.$target['public_id'].' cambió a '.$statuses[$target['status']].'.','support',array('url'=>'soporte.php?id='.$ticketId),$pdo);flash('ok',$message);header('Location: superadmin_soporte.php?id='.$ticketId);exit;} $error=$message;
  }
 }
}
$filters=array('status'=>isset($_GET['status'])?(string)$_GET['status']:'','priority'=>isset($_GET['priority'])?(string)$_GET['priority']:'','category'=>isset($_GET['category'])?(string)$_GET['category']:'');
if($filters['status']!==''&&!isset($statuses[$filters['status']]))$filters['status']='';if($filters['priority']!==''&&!isset($priorities[$filters['priority']]))$filters['priority']='';if($filters['category']!==''&&!isset($categories[$filters['category']]))$filters['category']='';
$selectedId=isset($_GET['id'])?(int)$_GET['id']:0;$selected=$selectedId?tickex_support_get_ticket($pdo,$selectedId,$adminId,true):null;if($selectedId&&!$selected)abort_404('Consulta no encontrada.');
$tickets=tickex_support_list_tickets($pdo,$adminId,true,$filters);$counts=tickex_support_counts($pdo,$adminId,true);$csrf=tickex_csrf_token();$flashes=flash_get_all();$title='Soporte de clientes';
include __DIR__.'/inc/layout_top.php';
?>
<style>
.sa-support{max-width:1180px;margin:0 auto;display:grid;gap:16px}.sa-hero{padding:27px;background:linear-gradient(135deg,#171b35,#332265)}.sa-hero h1{margin:5px 0}.sa-kicker{font-size:11px;color:#5edbef;font-weight:900;text-transform:uppercase;letter-spacing:.12em}.sa-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:9px;margin-top:18px}.sa-stat{padding:13px;border-radius:13px;border:1px solid rgba(255,255,255,.1);background:rgba(0,0,0,.17)}.sa-stat span{display:block;color:var(--muted);font-size:11px}.sa-stat strong{font-size:23px}.sa-filter{display:grid;grid-template-columns:repeat(3,1fr) auto;gap:9px;align-items:end}.sa-list{display:grid;gap:8px}.sa-row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:12px;padding:14px;border:1px solid var(--line);border-radius:13px;color:inherit;text-decoration:none}.sa-row:hover{border-color:#745be8}.sa-row h3{margin:3px 0;font-size:15px}.sa-meta{color:var(--muted);font-size:12px}.sa-badges{display:flex;gap:6px;align-items:start;flex-wrap:wrap;justify-content:flex-end}.sa-badge{padding:5px 8px;border:1px solid var(--line);border-radius:999px;font-size:10px;text-transform:uppercase;font-weight:850}.sa-badge.urgent{color:#ff8899;border-color:rgba(255,80,110,.4)}.sa-badge.high{color:#ffc36a}.sa-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;flex-wrap:wrap}.sa-thread{display:grid;gap:10px;margin-top:20px}.sa-message{max-width:86%;padding:13px 15px;border:1px solid var(--line);border-radius:15px;background:#11182d}.sa-message.support{margin-left:auto;background:rgba(108,73,213,.2)}.sa-message small{display:block;color:var(--muted);margin-bottom:6px}.sa-message p{white-space:pre-wrap;margin:0}.sa-actions{display:grid;grid-template-columns:1fr 1fr auto;gap:9px;align-items:end;margin-top:18px}.sa-reply{display:grid;gap:9px;margin-top:12px}
@media(max-width:760px){.sa-stats{grid-template-columns:repeat(2,1fr)}.sa-filter,.sa-actions{grid-template-columns:1fr}.sa-message{max-width:96%}}
</style>
<main class="sa-support"><section class="card sa-hero"><div class="sa-kicker">Operación central</div><h1>Soporte de clientes</h1><p class="muted">Consultas de todos los organizadores, ordenadas por urgencia y actividad.</p><div class="sa-stats"><div class="sa-stat"><span>Abiertas</span><strong><?php echo (int)$counts['open'];?></strong></div><div class="sa-stat"><span>En revisión</span><strong><?php echo (int)$counts['in_progress'];?></strong></div><div class="sa-stat"><span>Esperando cliente</span><strong><?php echo (int)$counts['waiting_client'];?></strong></div><div class="sa-stat"><span>Resueltas</span><strong><?php echo (int)($counts['resolved']+$counts['closed']);?></strong></div></div></section>
<?php foreach($flashes as $f):?><div class="flash <?php echo e($f['type']);?>"><?php echo e($f['msg']);?></div><?php endforeach;?><?php if($error!==''):?><div class="flash err"><?php echo e($error);?></div><?php endif;?>
<?php if($selected):?><section class="card"><div class="sa-head"><div><a class="muted" href="superadmin_soporte.php">← Volver a la bandeja</a><div class="sa-kicker" style="margin-top:14px"><?php echo e($selected['public_id']);?></div><h2 style="margin:5px 0"><?php echo e($selected['subject']);?></h2><div class="sa-meta"><?php echo e($selected['admin_name']?:$selected['admin_email']);?> · <?php echo e($categories[$selected['category']]);?><?php if($selected['event_name']):?> · <?php echo e($selected['event_name']);?><?php endif;?></div></div><div class="sa-badges"><span class="sa-badge <?php echo e($selected['priority']);?>"><?php echo e($priorities[$selected['priority']]);?></span><span class="sa-badge"><?php echo e($statuses[$selected['status']]);?></span></div></div><div class="sa-thread"><?php foreach($selected['messages'] as $m):?><article class="sa-message <?php echo $m['author_role']==='support'?'support':'';?>"><small><?php echo $m['author_role']==='support'?'Equipo Tickex':e($selected['admin_name']?:$selected['admin_email']);?> · <?php echo e(date('d/m/Y H:i',strtotime($m['created_at'])));?></small><p><?php echo e($m['body']);?></p></article><?php endforeach;?></div><form method="post" class="sa-reply"><input type="hidden" name="_csrf" value="<?php echo e($csrf);?>"><input type="hidden" name="action" value="reply"><input type="hidden" name="ticket_id" value="<?php echo (int)$selected['id'];?>"><label>Responder<textarea name="body" rows="5" maxlength="8000" required></textarea></label><button class="btn" type="submit">Enviar respuesta</button></form><form method="post" class="sa-actions"><input type="hidden" name="_csrf" value="<?php echo e($csrf);?>"><input type="hidden" name="action" value="update"><input type="hidden" name="ticket_id" value="<?php echo (int)$selected['id'];?>"><label>Estado<select name="status"><?php foreach($statuses as $k=>$v):?><option value="<?php echo e($k);?>" <?php echo $selected['status']===$k?'selected':'';?>><?php echo e($v);?></option><?php endforeach;?></select></label><label>Prioridad<select name="priority"><?php foreach($priorities as $k=>$v):?><option value="<?php echo e($k);?>" <?php echo $selected['priority']===$k?'selected':'';?>><?php echo e($v);?></option><?php endforeach;?></select></label><button class="btn secondary" type="submit">Actualizar</button></form></section>
<?php else:?><section class="card"><form method="get" class="sa-filter"><label>Estado<select name="status"><option value="">Todos</option><?php foreach($statuses as $k=>$v):?><option value="<?php echo e($k);?>" <?php echo $filters['status']===$k?'selected':'';?>><?php echo e($v);?></option><?php endforeach;?></select></label><label>Prioridad<select name="priority"><option value="">Todas</option><?php foreach($priorities as $k=>$v):?><option value="<?php echo e($k);?>" <?php echo $filters['priority']===$k?'selected':'';?>><?php echo e($v);?></option><?php endforeach;?></select></label><label>Tipo<select name="category"><option value="">Todos</option><?php foreach($categories as $k=>$v):?><option value="<?php echo e($k);?>" <?php echo $filters['category']===$k?'selected':'';?>><?php echo e($v);?></option><?php endforeach;?></select></label><button class="btn" type="submit">Filtrar</button></form></section><section class="card"><div class="sa-kicker">Bandeja</div><h2 style="margin:5px 0 16px">Consultas</h2><?php if(!$tickets):?><p class="muted">No hay consultas con estos filtros.</p><?php else:?><div class="sa-list"><?php foreach($tickets as $t):?><a class="sa-row" href="superadmin_soporte.php?id=<?php echo (int)$t['id'];?>"><div><div class="sa-meta"><?php echo e($t['public_id']);?> · <?php echo e($t['admin_name']?:$t['admin_email']);?></div><h3><?php echo e($t['subject']);?></h3><div class="sa-meta"><?php echo e($categories[$t['category']]);?><?php if($t['event_name']):?> · <?php echo e($t['event_name']);?><?php endif;?> · <?php echo (int)$t['message_count'];?> mensajes</div></div><div class="sa-badges"><span class="sa-badge <?php echo e($t['priority']);?>"><?php echo e($priorities[$t['priority']]);?></span><span class="sa-badge"><?php echo e($statuses[$t['status']]);?></span></div></a><?php endforeach;?></div><?php endif;?></section><?php endif;?></main>
<?php include __DIR__.'/inc/layout_bottom.php';?>
