<?php
require_once __DIR__.'/inc/bootstrap.php';
require_once __DIR__.'/inc/subscriptions.php';
require_login();
$pdo=db();$cu=current_user();$adminId=tickex_admin_id($cu);$role=tickex_admin_role($cu);
if($role!=='admin_evento'||$adminId<=0)abort_404('No tenés permiso.');
$access=tickex_subscription_access($pdo,$adminId,0);$sub=$access['subscription'];$features=$sub?json_decode((string)$sub['features_json'],true):array();if(!is_array($features))$features=array();
$statuses=tickex_subscription_statuses();$title='Mi plan';include __DIR__.'/inc/layout_top.php';
?>
<style>
.sub-page{max-width:1100px;margin:0 auto;display:grid;gap:16px}.sub-hero{padding:30px;background:radial-gradient(circle at 88% 4%,rgba(65,216,238,.16),transparent 30%),linear-gradient(135deg,#171b38,#35226e)}.sub-kicker{color:#5edbef;text-transform:uppercase;letter-spacing:.13em;font-size:11px;font-weight:900}.sub-hero h1{font-size:clamp(32px,5vw,48px);letter-spacing:-.04em;margin:7px 0}.sub-hero p{color:#c5c8d8;margin:0}.sub-grid{display:grid;grid-template-columns:1.25fr .75fr;gap:16px}.sub-plan-head{display:flex;justify-content:space-between;gap:12px;align-items:start}.sub-plan-head h2{font-size:30px;margin:4px 0}.sub-pill{border:1px solid rgba(95,226,167,.35);color:#6be5a8;background:rgba(50,220,140,.08);border-radius:999px;padding:6px 10px;font-size:11px;font-weight:850;text-transform:uppercase}.sub-metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:9px;margin:20px 0}.sub-metric{padding:14px;border:1px solid var(--line);border-radius:14px;background:rgba(255,255,255,.025)}.sub-metric span,.sub-meter-label{display:block;color:var(--muted);font-size:11px}.sub-metric strong{display:block;font-size:22px;margin-top:5px}.sub-meter{height:10px;background:#090e1d;border:1px solid var(--line);border-radius:999px;overflow:hidden;margin:8px 0}.sub-meter>i{display:block;height:100%;background:linear-gradient(90deg,#5d48e7,#48d9ed);border-radius:inherit}.sub-features{display:grid;gap:9px;padding:0;list-style:none}.sub-features li{padding:12px;border:1px solid var(--line);border-radius:12px}.sub-features li:before{content:'✓';color:#67e2a6;margin-right:9px;font-weight:900}.sub-note{padding:14px;border-radius:13px;background:rgba(255,190,80,.07);border:1px solid rgba(255,190,80,.22);color:#ffd08a}.sub-actions{display:grid;gap:9px}.sub-action{padding:14px;border:1px solid var(--line);border-radius:13px;text-decoration:none;color:inherit}.sub-action strong{display:block}.sub-action small{color:var(--muted)}@media(max-width:780px){.sub-grid{grid-template-columns:1fr}.sub-metrics{grid-template-columns:1fr}}
</style>
<main class="sub-page"><section class="card sub-hero"><div class="sub-kicker">Cuenta y capacidad</div><h1>Mi plan Tickex</h1><p>Tu comisión, uso mensual y herramientas reunidos en una sola vista.</p></section>
<?php if(!$sub):?><section class="card"><h2>Plan pendiente</h2><p class="muted">Tu cuenta todavía no tiene un plan asignado. Podés seguir operando mientras Tickex termina la configuración.</p></section><?php else:?>
<section class="sub-grid"><div class="card"><div class="sub-plan-head"><div><div class="sub-kicker">Plan actual</div><h2><?php echo e($sub['plan_name']);?></h2><p class="muted"><?php echo e($sub['plan_description']);?></p></div><span class="sub-pill"><?php echo e(isset($statuses[$sub['status']])?$statuses[$sub['status']]:$sub['status']);?></span></div><div class="sub-metrics"><div class="sub-metric"><span>Costo de servicio</span><strong><?php echo e(number_format((float)$sub['service_fee_percent'],2,',','.'));?>%</strong></div><div class="sub-metric"><span>Precio mensual</span><strong><?php echo $sub['monthly_price']===null?'A definir':'$'.e(number_format((float)$sub['monthly_price'],0,',','.'));?></strong></div><div class="sub-metric"><span>QR este mes</span><strong><?php echo (int)$access['usage']['used'];?> / <?php echo $access['limit']===null?'∞':(int)$access['limit'];?></strong></div></div><span class="sub-meter-label">Uso del período <?php echo e(date('d/m',strtotime($access['usage']['from'])));?> al <?php echo e(date('d/m',strtotime($access['usage']['to'])));?></span><div class="sub-meter"><i style="width:<?php echo $access['limit']?min(100,round($access['usage']['used']*100/$access['limit'])):0;?>%"></i></div><?php if($access['observing']):?><p class="sub-note">Modo observación activo: el límite se mide, pero todavía no bloquea emisiones.</p><?php endif;?></div>
<aside class="card"><div class="sub-kicker">Incluido</div><h2>Herramientas</h2><ul class="sub-features"><?php foreach($features as $feature):?><li><?php echo e($feature);?></li><?php endforeach;?></ul><div class="sub-actions"><a class="sub-action" href="facturacion_admin.php"><strong>Ver facturación</strong><small>Cobros y comisiones</small></a><a class="sub-action" href="soporte.php"><strong>Consultar a Tickex</strong><small>Planes, límites o condiciones</small></a></div></aside></section>
<?php endif;?></main><?php include __DIR__.'/inc/layout_bottom.php';?>
