#!/usr/bin/env bash
#
# INSTRUCCIONES DE TESTING - Refactor panel_evento.php
#

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║  Testing Refactor panel_evento.php - Entradas Unificadas      ║"
echo "╚════════════════════════════════════════════════════════════════╝"

echo ""
echo "1️⃣ INICIAR SERVIDOR LOCAL"
echo "   $ cd F:\GIT\newtickex\str"
echo "   $ php -S 127.0.0.1:8080 -t ."
echo ""

echo "2️⃣ ACCEDER AL PANEL"
echo "   $ open http://127.0.0.1:8080/panel_evento.php?evento_id=1"
echo "   (Cambiar evento_id=1 según tus eventos disponibles)"
echo ""

echo "3️⃣ VERIFICAR UNIFICACIÓN DE ENTRADAS"
echo "   ✓ Debe mostrar UNA SOLA tabla con:"
echo "      - Columna 'Origen' (STR o TICKEX)"
echo "      - Columna 'Pago' (✓ o ✗)"
echo "      - Columna 'Estado' (OK o Pendiente)"
echo "      - Columna 'Acciones' (diferenciada por origen)"
echo ""
echo "   ✓ Si no hay entradas Tickex, solo muestra STR (normal)"
echo "   ✓ Los filtros (búsqueda, tipo, estado) aplican a todas"
echo ""

echo "4️⃣ PROBAR INGRESOS MANUALES"
echo ""
echo "   A) AGREGAR INGRESO:"
echo "      - Scroll down hasta sección 'Ingresos manuales'"
echo "      - Completar formulario:"
echo "        • Concepto: 'Venta puerta'"
echo "        • Monto: '500'"
echo "        • Descripción: '10 personas a puerta'"
echo "      - Click 'Agregar'"
echo "      → Debe mostrar mensaje de éxito"
echo "      → Debe aparecer en tabla abajo"
echo ""
echo "   B) VER LISTADO:"
echo "      - Debe mostrar todas las entradas manuales"
echo "      - Con fecha y hora de creación"
echo "      - Total acumulado en footer"
echo ""
echo "   C) ELIMINAR INGRESO:"
echo "      - Click botón 🗑 en la fila"
echo "      - Confirmar"
echo "      → Debe desaparecer y refrescar total"
echo ""

echo "5️⃣ VERIFICAR COMPATIBILIDAD"
echo "   ✓ Panel mantiene estilo original (header, layout)"
echo "   ✓ Permisos funcionan igual (admin_evento, super_admin)"
echo "   ✓ Stats globales siguen siendo solo de STR"
echo "   ✓ Filtros existentes funcionan"
echo ""

echo "6️⃣ CASOS EDGE"
echo ""
echo "   • Si no existe tabla senforms_bridge_tickets:"
echo "     → Panel sigue mostrando solo STR (OK)"
echo ""
echo "   • Si BD no tiene columna 'evento_id' en bridge:"
echo "     → Se puede agregar manualmente o usar fallback"
echo ""
echo "   • Si usuario no es admin_evento:"
echo "     → Panel no visible (permisos mantienen restricción)"
echo ""

echo "7️⃣ ARCHIVOS IMPORTANTES"
echo ""
echo "   📝 panel_evento.php"
echo "      └─ REFACTORIZADO (unificación + ingresos)"
echo ""
echo "   📚 inc/unified_tickets.php"
echo "      └─ NEW: Lógica de unificación"
echo ""
echo "   📚 inc/manual_income.php"
echo "      └─ NEW: Gestión de ingresos"
echo ""
echo "   🔌 add_manual_income.php"
echo "      └─ NEW: Endpoint POST para agregar"
echo ""
echo "   🔌 delete_manual_income.php"
echo "      └─ NEW: Endpoint POST para eliminar"
echo ""

echo "8️⃣ DB LOCAL"
echo ""
echo "   Archivo: str/save_the_rave.sqlite"
echo "   (Creada automáticamente tabla 'manual_income' si no existe)"
echo ""
echo "   NO SE COMMITEA - .gitignore la ignora"
echo ""

echo "9️⃣ TROUBLESHOOTING"
echo ""
echo "   Problema: 'No se ve tabla de Tickex'"
echo "   → Normal si no existen entradas pagas en bridge"
echo "   → Verificar BD tiene vista/tabla"
echo ""
echo "   Problema: 'Error al agregar ingreso'"
echo "   → Verificar permisos de usuario"
echo "   → Revisar console del navegador (F12)"
echo ""
echo "   Problema: 'No aparecen ingresos manuales'"
echo "   → BD no tiene permiso de escritura"
echo "   → O tabla fue eliminada"
echo ""

echo ""
echo "✅ TODO LISTO!"
echo ""
