<?php require __DIR__ . '/communication_operations_ui.php'; ?>
<main class="comm-ops">
 <section class="card comm-hero"><div class="comm-hero-top"><div><span class="comm-kicker">Operación de envíos</span><h1>Estado del motor</h1><p>Supervisá la cola, el avance de cada ejecución y los errores que requieren atención.</p></div><a class="btn secondary" href="comunicacion_historial.php">Ver historial</a></div><?php communication_ui_flow('');?></section>
 <?php communication_ui_ops_nav('engine');?>
 <?php if($flashOk!==''||$flashErr!==''):?><div class="comm-alerts"><?php if($flashOk!==''):?><div class="flash ok"><?php echo e($flashOk);?></div><?php endif;?><?php if($flashErr!==''):?><div class="flash err"><?php echo e($flashErr);?></div><?php endif;?></div><?php endif;?>
 <section class="comm-stats six"><div class="card comm-stat"><span>En cola</span><strong><?php echo (int)$state['counts']['campaigns_queued'];?></strong><small>Campañas esperando</small></div><div class="card comm-stat"><span>En ejecución</span><strong><?php echo (int)$state['counts']['campaigns_running'];?></strong><small>Campañas activas</small></div><div class="card comm-stat"><span>Finalizadas</span><strong><?php echo (int)$state['counts']['campaigns_finished'];?></strong><small>Procesos cerrados</small></div><div class="card comm-stat"><span>Fallidas</span><strong><?php echo (int)$state['counts']['campaigns_failed'];?></strong><small>Requieren revisión</small></div><div class="card comm-stat"><span>Runs activos</span><strong><?php echo (int)$state['counts']['active_runs'];?></strong><small>Ejecuciones abiertas</small></div><div class="card comm-stat"><span>Comandos pendientes</span><strong><?php echo (int)$state['counts']['queue_pending'];?></strong><small>Trabajo por procesar</small></div></section>
 <section class="card comm-panel"><header class="comm-panel-head"><h2>Procesamiento manual</h2><p>Uso técnico para adelantar la cola. El procesamiento automático continúa funcionando por separado.</p></header><div class="comm-panel-body"><form method="post" style="display:flex;gap:9px;align-items:end;flex-wrap:wrap"><input type="hidden" name="csrf" value="<?php echo e($csrf);?>"><div class="comm-field"><label>Máximo de comandos</label><input type="number" name="max_commands" value="5" min="1" max="100" style="width:155px"></div><div class="comm-field"><label>Destinatarios por lote</label><input type="number" name="batch_size" value="200" min="1" style="width:170px"></div><button class="btn" name="action" value="run_worker_now">Procesar cola ahora</button></form></div></section>
 <div class="comm-section-head"><div><h2>Ejecuciones recientes</h2><p>Progreso y resultado de cada envío.</p></div></div>
 <section class="card comm-table-wrap"><table class="comm-table"><thead><tr><th>Run / campaña</th><th>Estado</th><th>Progreso</th><th>Destinatarios</th><th>Enviados</th><th>Fallidos</th><th>Pendientes</th><th>Acciones</th></tr></thead><tbody>
 <?php if(empty($state['run_progress'])):?><tr><td colspan="8" class="comm-empty">Todavía no hay ejecuciones registradas.</td></tr><?php else:?>
 <?php foreach($state['run_progress'] as $r):$canRemove=in_array(strtolower((string)$r['status']),array('completed','done','failed','cancelled'),true);?>
 <tr><td><strong>#<?php echo (int)$r['run_id'];?> · <?php echo e($r['campaign_name']);?></strong></td><td><span class="comm-status <?php echo e(communication_ui_status_class($r['status']));?>"><?php echo e(communication_ui_status_label($r['status']));?></span></td><td style="min-width:130px"><strong><?php echo (int)$r['progress_pct'];?>%</strong><div class="comm-progress" style="margin-top:6px"><span style="width:<?php echo (int)$r['progress_pct'];?>%"></span></div></td><td><?php echo (int)$r['resolved_recipients'];?></td><td><?php echo (int)$r['accepted_count'];?></td><td><?php echo (int)$r['failed_count'];?></td><td><?php echo (int)$r['pending_count'];?></td><td><div class="comm-actions"><a class="btn secondary" href="comunicacion_historial.php?run_id=<?php echo (int)$r['run_id'];?>">Detalle</a><form method="post"><input type="hidden" name="csrf" value="<?php echo e($csrf);?>"><input type="hidden" name="run_id" value="<?php echo (int)$r['run_id'];?>"><button class="btn secondary" name="action" value="retry_run">Reintentar</button></form><form method="post"><input type="hidden" name="csrf" value="<?php echo e($csrf);?>"><input type="hidden" name="run_id" value="<?php echo (int)$r['run_id'];?>"><button class="btn secondary" name="action" value="resume_run">Reanudar</button></form><form method="post"><input type="hidden" name="csrf" value="<?php echo e($csrf);?>"><input type="hidden" name="run_id" value="<?php echo (int)$r['run_id'];?>"><button class="btn secondary" name="action" value="cancel_run">Cancelar</button></form><?php if($canRemove):?><form method="post" onsubmit="return confirm('¿Eliminar esta ejecución de la vista? Las métricas y la auditoría se conservarán.');"><input type="hidden" name="csrf" value="<?php echo e($csrf);?>"><input type="hidden" name="run_id" value="<?php echo (int)$r['run_id'];?>"><button class="btn secondary comm-delete" name="action" value="remove_run">Eliminar</button></form><?php endif;?></div></td></tr>
 <?php endforeach;?><?php endif;?></tbody></table></section>
 <section class="comm-grid-2"><div class="card comm-panel"><header class="comm-panel-head"><h3>Destinatarios por estado</h3><p>Resultado global de procesamiento.</p></header><div class="comm-panel-body"><?php if(empty($state['recipient_by_status'])):?><div class="comm-empty">Sin destinatarios procesados.</div><?php else:?><div class="comm-list"><?php foreach($state['recipient_by_status'] as $row):?><div style="display:flex;justify-content:space-between;gap:10px"><span class="comm-status <?php echo e(communication_ui_status_class($row['status']));?>"><?php echo e(communication_ui_status_label($row['status']));?></span><strong><?php echo (int)$row['count'];?></strong></div><?php endforeach;?></div><?php endif;?></div></div><div class="card comm-panel"><header class="comm-panel-head"><h3>Campañas por etapa</h3><p>Distribución rápida del trabajo.</p></header><div class="comm-panel-body comm-grid-2"><?php $groups=array('Por preparar'=>$queuedCampaigns,'En ejecución'=>$runningCampaigns,'Finalizadas'=>$finishedCampaigns,'Fallidas'=>$failedCampaigns);foreach($groups as $label=>$items):?><div><strong><?php echo e($label);?></strong><?php if(!$items):?><div class="comm-muted" style="margin-top:7px">Sin campañas.</div><?php else:?><?php foreach($items as $c):?><div style="padding:8px 0;border-bottom:1px solid rgba(255,255,255,.06)"><a href="comunicacion_historial.php?campaign_id=<?php echo (int)$c['id'];?>"><?php echo e($c['name']);?></a><div class="comm-muted"><?php echo e(communication_ui_status_label($c['status']));?> · <?php echo e($c['updated_at']);?></div></div><?php endforeach;?><?php endif;?></div><?php endforeach;?></div></div></section>
 <section class="card comm-panel"><header class="comm-panel-head"><h2>Comandos del motor</h2><p>Solicitudes pendientes o recientes vinculadas con cada campaña.</p></header><div class="comm-table-wrap"><table class="comm-table"><thead><tr><th>Comando</th><th>Campaña</th><th>Estado</th><th>Actualizado</th><th>Error</th><th>Acción</th></tr></thead><tbody><?php if(!$pendingCommands):?><tr><td colspan="6" class="comm-empty">No hay comandos relevantes.</td></tr><?php else:?><?php foreach($pendingCommands as $cmd):?><tr><td>#<?php echo (int)$cmd['id'];?></td><td><strong><?php echo e($cmd['campaign_name']);?></strong><div class="comm-muted"><?php echo e(communication_ui_status_label($cmd['campaign_status']));?></div></td><td><span class="comm-status <?php echo e(communication_ui_status_class($cmd['status']));?>"><?php echo e(communication_ui_status_label($cmd['status']));?></span></td><td><?php echo e($cmd['updated_at']);?></td><td><?php echo e((string)$cmd['error_text']);?></td><td><form method="post"><input type="hidden" name="csrf" value="<?php echo e($csrf);?>"><input type="hidden" name="campaign_id" value="<?php echo (int)$cmd['campaign_id'];?>"><button class="btn secondary" name="action" value="requeue_campaign">Reencolar</button></form></td></tr><?php endforeach;?><?php endif;?></tbody></table></div></section>
</main>
