<?php require __DIR__ . '/communication_operations_ui.php';
$metrics=isset($runDetail['metrics'])&&is_array($runDetail['metrics'])?$runDetail['metrics']:array();
$acceptedForRates=!empty($runDetail['run']['accepted_count'])?(int)$runDetail['run']['accepted_count']:0;
$uniqueOpens=isset($metrics['unique_opens'])?(int)$metrics['unique_opens']:0;
$uniqueClicks=isset($metrics['unique_clicks'])?(int)$metrics['unique_clicks']:0;
$confirmedOrders=isset($metrics['confirmed_orders'])?(int)$metrics['confirmed_orders']:0;
$revenue=isset($metrics['revenue'])?(float)$metrics['revenue']:0;
?>
<main class="comm-ops">
 <section class="card comm-hero"><div class="comm-hero-top"><div><span class="comm-kicker">Resultados y trazabilidad</span><h1>Historial de envíos</h1><p>Revisá cada ejecución, sus destinatarios y el impacto real de aperturas, clics y compras.</p></div><a class="btn secondary" href="comunicacion_campanas.php">Ir a campañas</a></div><?php communication_ui_flow('');?></section>
 <?php communication_ui_ops_nav('history');?>
 <?php if($flashOk!==''||$flashErr!==''):?><div class="comm-alerts"><?php if($flashOk!==''):?><div class="flash ok"><?php echo e($flashOk);?></div><?php endif;?><?php if($flashErr!==''):?><div class="flash err"><?php echo e($flashErr);?></div><?php endif;?></div><?php endif;?>
 <section class="card comm-toolbar"><form method="get" style="display:grid;grid-template-columns:minmax(300px,1fr) auto auto;gap:8px;align-items:end"><div class="comm-field"><label>Campaña</label><select name="campaign_id" onchange="this.form.submit()"><?php if(!$campaignOptions):?><option value="">No hay campañas</option><?php endif;?><?php foreach($campaignOptions as $c):?><option value="<?php echo (int)$c['id'];?>"<?php echo (int)$campaignId===(int)$c['id']?' selected':'';?>><?php echo e($c['name']);?> · <?php echo e(communication_ui_status_label($c['status']));?></option><?php endforeach;?></select></div><button class="btn" type="submit">Ver historial</button><?php if($campaignId>0):?><a class="btn secondary" href="comunicacion_campanas.php?id=<?php echo (int)$campaignId;?>#campaign-editor">Editar campaña</a><?php endif;?></form></section>
 <?php if($runId>0&&!empty($runDetail['run'])):?><section class="comm-stats"><div class="card comm-stat"><span>Aperturas únicas*</span><strong><?php echo $uniqueOpens;?></strong><small><?php echo $acceptedForRates>0?e(number_format(100*$uniqueOpens/$acceptedForRates,1,',','.')):'0,0';?>% de enviados</small></div><div class="card comm-stat"><span>Clics únicos</span><strong><?php echo $uniqueClicks;?></strong><small><?php echo $acceptedForRates>0?e(number_format(100*$uniqueClicks/$acceptedForRates,1,',','.')):'0,0';?>% de enviados</small></div><div class="card comm-stat"><span>Compras</span><strong><?php echo $confirmedOrders;?></strong><small><?php echo $uniqueClicks>0?e(number_format(100*$confirmedOrders/$uniqueClicks,1,',','.')):'0,0';?>% de clics</small></div><div class="card comm-stat"><span>Ingresos atribuidos</span><strong>$<?php echo e(number_format($revenue,0,',','.'));?></strong><small>Ejecución #<?php echo (int)$runId;?></small></div></section><p class="comm-muted" style="margin:-8px 3px 0">* Las aperturas son aproximadas. Los clics y las compras confirmadas son señales más confiables.</p><?php endif;?>
 <div class="comm-section-head"><div><h2>Ejecuciones de la campaña</h2><p>Cada intento queda separado para poder auditarlo y reanudarlo.</p></div><?php if($campaignId>0):?><form method="post"><input type="hidden" name="csrf" value="<?php echo e($csrf);?>"><input type="hidden" name="campaign_id" value="<?php echo (int)$campaignId;?>"><button class="btn" name="action" value="requeue_campaign">Volver a encolar</button></form><?php endif;?></div>
 <?php if(empty($history['runs'])):?><section class="card comm-empty">Esta campaña todavía no tiene ejecuciones.</section><?php else:?><section class="comm-list"><?php foreach($history['runs'] as $r):$sent=(int)$r['sent_count'];$pct=(int)$r['resolved_recipients']>0?(int)round(100*((int)$r['sent_count']+(int)$r['failed_count'])/(int)$r['resolved_recipients']):0;?><article class="card comm-item" style="display:grid;grid-template-columns:minmax(165px,.5fr) minmax(220px,.8fr) minmax(210px,.7fr) auto;gap:16px;align-items:center"><div><a class="comm-item-title" href="comunicacion_historial.php?campaign_id=<?php echo (int)$campaignId;?>&run_id=<?php echo (int)$r['id'];?>">Ejecución #<?php echo (int)$r['id'];?></a><div class="comm-item-sub"><?php echo e($r['started_at']);?> · <?php echo $r['duration_seconds']===null?'En curso':((int)$r['duration_seconds'].'s');?></div></div><div><span class="comm-status <?php echo e(communication_ui_status_class($r['status']));?>"><?php echo e(communication_ui_status_label($r['status']));?></span><div class="comm-progress" style="margin-top:8px"><span style="width:<?php echo $pct;?>%"></span></div><div class="comm-muted" style="margin-top:5px"><?php echo (int)$r['sent_count'];?> enviados · <?php echo (int)$r['failed_count'];?> fallidos · <?php echo (int)$r['pending_count'];?> pendientes</div></div><div class="comm-muted"><?php echo (int)$r['unique_opens'];?> aperturas · <?php echo (int)$r['unique_clicks'];?> clics<br><?php echo (int)$r['confirmed_orders'];?> compras · $<?php echo e(number_format((float)$r['revenue'],0,',','.'));?></div><div class="comm-actions"><form method="post"><input type="hidden" name="csrf" value="<?php echo e($csrf);?>"><input type="hidden" name="run_id" value="<?php echo (int)$r['id'];?>"><button class="btn secondary" name="action" value="retry_run">Reintentar</button></form><form method="post"><input type="hidden" name="csrf" value="<?php echo e($csrf);?>"><input type="hidden" name="run_id" value="<?php echo (int)$r['id'];?>"><button class="btn secondary" name="action" value="resume_run">Reanudar</button></form><form method="post"><input type="hidden" name="csrf" value="<?php echo e($csrf);?>"><input type="hidden" name="run_id" value="<?php echo (int)$r['id'];?>"><button class="btn secondary" name="action" value="cancel_run">Cancelar</button></form></div></article><?php endforeach;?></section><?php endif;?>
 <section class="card comm-panel"><header class="comm-panel-head"><h2>Destinatarios <?php echo $runId>0?'de la ejecución #'.(int)$runId:'';?></h2><p>Detalle técnico de entrega por dirección.</p></header><div class="comm-table-wrap"><table class="comm-table"><thead><tr><th>Email / nombre</th><th>Estado</th><th>Proveedor</th><th>Respuesta</th><th>Intentos</th><th>Último intento</th></tr></thead><tbody><?php if(empty($runDetail['recipients'])):?><tr><td colspan="6" class="comm-empty">No hay destinatarios para mostrar.</td></tr><?php else:?><?php foreach($runDetail['recipients'] as $rr):?><tr><td><strong><?php echo e($rr['recipient_email']);?></strong><div class="comm-muted"><?php echo e($rr['recipient_name']);?></div></td><td><span class="comm-status <?php echo e(communication_ui_status_class($rr['status']));?>"><?php echo e(communication_ui_status_label($rr['status']));?></span></td><td><?php echo e($rr['provider_name']);?></td><td style="max-width:360px;word-break:break-word"><strong><?php echo e($rr['last_response_code']);?></strong><div class="comm-muted"><?php echo e($rr['last_response_message']);?></div></td><td><?php echo (int)$rr['attempt_count'];?></td><td><?php echo e($rr['last_attempt_at']);?></td></tr><?php endforeach;?><?php endif;?></tbody></table></div><?php $total=isset($runDetail['total'])?(int)$runDetail['total']:0;$hasPrev=$page>1;$hasNext=($offset+$perPage)<$total;if($total>$perPage):?><div class="comm-panel-body" style="display:flex;justify-content:flex-end;gap:8px;align-items:center"><?php if($hasPrev):?><a class="btn secondary" href="comunicacion_historial.php?campaign_id=<?php echo (int)$campaignId;?>&run_id=<?php echo (int)$runId;?>&p=<?php echo (int)($page-1);?>">Anterior</a><?php endif;?><span class="comm-muted">Página <?php echo (int)$page;?> · <?php echo $total;?> destinatarios</span><?php if($hasNext):?><a class="btn secondary" href="comunicacion_historial.php?campaign_id=<?php echo (int)$campaignId;?>&run_id=<?php echo (int)$runId;?>&p=<?php echo (int)($page+1);?>">Siguiente</a><?php endif;?></div><?php endif;?></section>
</main>
