<?php

if(!function_exists('tickex_legal_types')){
 function tickex_legal_types(){return array('terms'=>'Términos y condiciones','privacy'=>'Política de privacidad','refunds'=>'Cambios, cancelaciones y reembolsos','organizers'=>'Acuerdo para organizadores');}
}
if(!function_exists('tickex_legal_ensure_schema')){
 function tickex_legal_ensure_schema($pdo){
  $pdo->exec("CREATE TABLE IF NOT EXISTS legal_documents(id INTEGER PRIMARY KEY AUTOINCREMENT,document_type TEXT NOT NULL,version INTEGER NOT NULL,title TEXT NOT NULL,summary TEXT,body TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'draft',effective_at TEXT,created_by_admin_id INTEGER,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(document_type,version))");
  $pdo->exec("CREATE TABLE IF NOT EXISTS legal_acceptances(id INTEGER PRIMARY KEY AUTOINCREMENT,subject_type TEXT NOT NULL,subject_id INTEGER,email TEXT,context TEXT NOT NULL,documents_json TEXT NOT NULL,ip_hash TEXT,user_agent_hash TEXT,accepted_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)");
  $pdo->exec("CREATE TABLE IF NOT EXISTS withdrawal_requests(id INTEGER PRIMARY KEY AUTOINCREMENT,public_id TEXT NOT NULL UNIQUE,email TEXT NOT NULL,full_name TEXT NOT NULL,purchase_reference TEXT,event_name TEXT,reason TEXT,status TEXT NOT NULL DEFAULT 'received',resolution_note TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,resolved_at TEXT,resolved_by_admin_id INTEGER)");
  $pdo->exec("CREATE TABLE IF NOT EXISTS privacy_requests(id INTEGER PRIMARY KEY AUTOINCREMENT,public_id TEXT NOT NULL UNIQUE,email TEXT NOT NULL,full_name TEXT NOT NULL,request_type TEXT NOT NULL,details TEXT,status TEXT NOT NULL DEFAULT 'received',resolution_note TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,resolved_at TEXT,resolved_by_admin_id INTEGER)");
  $pdo->exec('CREATE INDEX IF NOT EXISTS idx_legal_documents_active ON legal_documents(document_type,status,effective_at)');
  $pdo->exec('CREATE INDEX IF NOT EXISTS idx_legal_acceptances_subject ON legal_acceptances(subject_type,subject_id,accepted_at)');
  $pdo->exec('CREATE UNIQUE INDEX IF NOT EXISTS idx_legal_acceptances_context ON legal_acceptances(subject_type,email,context)');
  $pdo->exec('CREATE INDEX IF NOT EXISTS idx_withdrawal_status ON withdrawal_requests(status,created_at)');
  $pdo->exec('CREATE INDEX IF NOT EXISTS idx_privacy_request_status ON privacy_requests(status,created_at)');
  $seed=array(
   'terms'=>array('Términos y condiciones de Tickex','Reglas generales de uso, compra y acceso a eventos.',"BORRADOR PARA REVISIÓN PROFESIONAL\n\n1. Identificación del proveedor\n[Completar razón social, CUIT, domicilio y canales de contacto.]\n\n2. Alcance de Tickex\nTickex brinda tecnología para publicar eventos, gestionar entradas y procesar cobros a través de proveedores de pago. Cada organizador es responsable de la información, realización y condiciones particulares de su evento.\n\n3. Información de compra\nAntes de pagar se informarán evento, tipo y cantidad de entradas, precio, costo de servicio, total, medio de pago y datos del organizador.\n\n4. Entradas y acceso\nCada QR es único. Su duplicación, reventa no autorizada o uso fraudulento puede ocasionar su invalidación.\n\n5. Cancelaciones y reprogramaciones\nLas condiciones aplicables deberán informarse junto con cada evento, respetando los derechos irrenunciables de consumidores y usuarios.\n\n6. Atención y reclamos\n[Completar email, teléfono, responsable y horario de atención.]"),
   'privacy'=>array('Política de privacidad','Cómo se recopilan, utilizan y protegen los datos personales.',"BORRADOR PARA REVISIÓN PROFESIONAL\n\n1. Responsable del tratamiento\n[Completar identidad, domicilio y datos de contacto del responsable.]\n\n2. Datos tratados\nDatos identificatorios y de contacto, compras, entradas, accesos, comunicaciones, soporte y datos técnicos de seguridad.\n\n3. Finalidades\nCrear cuentas, procesar compras, emitir y validar entradas, prestar soporte, prevenir fraude y enviar comunicaciones cuando exista una base legal válida.\n\n4. Destinatarios\nOrganizadores del evento correspondiente, proveedores de pago, correo, hosting y otros encargados necesarios para prestar el servicio.\n\n5. Conservación y seguridad\nLos datos se conservarán únicamente durante los plazos necesarios y legales, aplicando medidas técnicas y organizativas razonables.\n\n6. Derechos\nLas personas pueden solicitar acceso, rectificación, actualización o supresión mediante [completar canal].\n\n7. Autoridad de control\nLa Agencia de Acceso a la Información Pública es la autoridad de aplicación de la Ley 25.326."),
   'refunds'=>array('Cambios, cancelaciones y reembolsos','Qué ocurre ante arrepentimiento, cancelación o reprogramación.',"BORRADOR PARA REVISIÓN PROFESIONAL\n\n1. Derecho de arrepentimiento\nPara entradas de espectáculos, eventos deportivos o artísticos, la solicitud debe realizarse dentro de los diez días corridos desde la entrega de la entrada o comprobante —lo que ocurra primero— y al menos veinticuatro horas antes del evento, conforme la Disposición 954/2025.\n\n2. Solicitud\nEl botón de arrepentimiento es público y no requiere iniciar sesión. Tickex entrega inmediatamente un código identificador para seguimiento.\n\n3. Entrada utilizada\nNo corresponde el arrepentimiento luego de haber utilizado o consumido el servicio.\n\n4. Cancelación o reprogramación\nEl organizador informará las opciones disponibles y será responsable de las condiciones y fondos necesarios para el reembolso.\n\n5. Split de pagos\nCuando interviene Mercado Pago, el reembolso puede requerir fondos tanto del organizador como de Tickex según la distribución original."),
   'organizers'=>array('Acuerdo para organizadores','Responsabilidades, comisiones y uso profesional de la plataforma.',"BORRADOR PARA REVISIÓN PROFESIONAL\n\n1. Cuenta y veracidad\nEl organizador debe brindar información auténtica, mantener seguros sus accesos y operar únicamente eventos propios o autorizados.\n\n2. Evento y consumidores\nEl organizador responde por la realización, habilitaciones, contenidos, precios, capacidad, devoluciones y atención de sus compradores.\n\n3. Cobros y comisión\nEl plan vigente define límites y costo de servicio. Los cobros Split se acreditan en la cuenta conectada del organizador y separan la comisión de Tickex.\n\n4. Uso aceptable\nNo se permite fraude, spam, discriminación, contenido ilícito ni el tratamiento de datos fuera de finalidades legítimas.\n\n5. Suspensión\nTickex puede pausar operaciones ante riesgos de seguridad, fraude, incumplimientos o requerimientos legales, preservando la trazabilidad de las acciones.\n\n6. Soporte\nLas incidencias y solicitudes se gestionan desde el centro de soporte de la plataforma."),
  );
  $check=$pdo->prepare('SELECT COUNT(*) FROM legal_documents WHERE document_type=?');$insert=$pdo->prepare("INSERT INTO legal_documents(document_type,version,title,summary,body,status) VALUES(?,1,?,?,?,'draft')");
  foreach($seed as $type=>$data){$check->execute(array($type));if(!(int)$check->fetchColumn())$insert->execute(array($type,$data[0],$data[1],$data[2]));}
 }
}
if(!function_exists('tickex_legal_documents')){
 function tickex_legal_documents($pdo,$includeDrafts=false){tickex_legal_ensure_schema($pdo);$where=$includeDrafts?'':" WHERE d.status='published' AND (d.effective_at IS NULL OR datetime(d.effective_at)<=datetime('now'))";$sql='SELECT d.* FROM legal_documents d'.$where.' ORDER BY d.document_type,d.version DESC';$rows=$pdo->query($sql)->fetchAll(PDO::FETCH_ASSOC);if(!$includeDrafts){$out=array();foreach($rows as $row)if(!isset($out[$row['document_type']]))$out[$row['document_type']]=$row;return $out;}return $rows;}
}
if(!function_exists('tickex_legal_save_document')){
 function tickex_legal_save_document($pdo,$type,$title,$summary,$body,$publish,$adminId){$types=tickex_legal_types();if(!isset($types[$type]))throw new RuntimeException('Documento inválido.');$title=trim((string)$title);$body=trim((string)$body);if($title===''||$body==='')throw new RuntimeException('Título y contenido son obligatorios.');tickex_legal_ensure_schema($pdo);$st=$pdo->prepare('SELECT COALESCE(MAX(version),0)+1 FROM legal_documents WHERE document_type=?');$st->execute(array($type));$version=(int)$st->fetchColumn();$pdo->beginTransaction();try{if($publish){$st=$pdo->prepare("UPDATE legal_documents SET status='archived',updated_at=CURRENT_TIMESTAMP WHERE document_type=? AND status='published'");$st->execute(array($type));}$st=$pdo->prepare('INSERT INTO legal_documents(document_type,version,title,summary,body,status,effective_at,created_by_admin_id) VALUES(?,?,?,?,?,?,?,?)');$st->execute(array($type,$version,$title,trim((string)$summary),$body,$publish?'published':'draft',$publish?date('Y-m-d H:i:s'):null,(int)$adminId));$pdo->commit();return (int)$pdo->lastInsertId();}catch(Exception $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}}
}
if(!function_exists('tickex_legal_public_document')){
 function tickex_legal_public_document($pdo,$type){$docs=tickex_legal_documents($pdo,false);return isset($docs[$type])?$docs[$type]:null;}
}
if(!function_exists('tickex_legal_record_acceptance')){
 function tickex_legal_record_acceptance($pdo,$subjectType,$subjectId,$email,$context,$server=array(),$documentTypes=null){tickex_legal_ensure_schema($pdo);$docs=tickex_legal_documents($pdo,false);$versions=array();foreach($docs as $type=>$doc){if(is_array($documentTypes)&&!in_array($type,$documentTypes,true))continue;$versions[$type]=array('id'=>(int)$doc['id'],'version'=>(int)$doc['version']);}if(!$versions)return false;$normalizedEmail=strtolower(trim((string)$email));$ip=isset($server['REMOTE_ADDR'])?(string)$server['REMOTE_ADDR']:'';$ua=isset($server['HTTP_USER_AGENT'])?(string)$server['HTTP_USER_AGENT']:'';$st=$pdo->prepare('INSERT OR IGNORE INTO legal_acceptances(subject_type,subject_id,email,context,documents_json,ip_hash,user_agent_hash) VALUES(?,?,?,?,?,?,?)');$st->execute(array((string)$subjectType,$subjectId?(int)$subjectId:null,$normalizedEmail,(string)$context,json_encode($versions),$ip!==''?hash('sha256',$ip):null,$ua!==''?hash('sha256',$ua):null));return true;}
}
if(!function_exists('tickex_legal_create_withdrawal')){
 function tickex_legal_create_withdrawal($pdo,$data){tickex_legal_ensure_schema($pdo);$email=strtolower(trim(isset($data['email'])?(string)$data['email']:''));$name=trim(isset($data['full_name'])?(string)$data['full_name']:'');$ref=trim(isset($data['purchase_reference'])?(string)$data['purchase_reference']:'');if(!filter_var($email,FILTER_VALIDATE_EMAIL)||$name===''||$ref==='')throw new RuntimeException('Completá nombre, email y referencia de compra.');$public='ARR-'.date('Ymd').'-'.strtoupper(substr(bin2hex(random_bytes(6)),0,10));$st=$pdo->prepare('INSERT INTO withdrawal_requests(public_id,email,full_name,purchase_reference,event_name,reason) VALUES(?,?,?,?,?,?)');$st->execute(array($public,$email,$name,$ref,trim(isset($data['event_name'])?(string)$data['event_name']:''),trim(isset($data['reason'])?(string)$data['reason']:'')));return $public;}
}
if(!function_exists('tickex_legal_withdrawals')){
 function tickex_legal_withdrawals($pdo,$status=''){tickex_legal_ensure_schema($pdo);$sql='SELECT * FROM withdrawal_requests';$params=array();if($status!==''){$sql.=' WHERE status=:status';$params[':status']=$status;}$sql.=' ORDER BY id DESC LIMIT 100';$st=$pdo->prepare($sql);$st->execute($params);return $st->fetchAll(PDO::FETCH_ASSOC);}
}
if(!function_exists('tickex_legal_update_withdrawal')){
 function tickex_legal_update_withdrawal($pdo,$id,$status,$note,$adminId){$allowed=array('received','reviewing','approved','rejected','refunded');if(!in_array($status,$allowed,true))throw new RuntimeException('Estado inválido.');$st=$pdo->prepare("UPDATE withdrawal_requests SET status=:status,resolution_note=:note,updated_at=CURRENT_TIMESTAMP,resolved_at=CASE WHEN :status IN ('approved','rejected','refunded') THEN CURRENT_TIMESTAMP ELSE NULL END,resolved_by_admin_id=:admin WHERE id=:id");$st->execute(array(':status'=>$status,':note'=>trim((string)$note),':admin'=>(int)$adminId,':id'=>(int)$id));}
}
if(!function_exists('tickex_legal_create_privacy_request')){
 function tickex_legal_create_privacy_request($pdo,$data){tickex_legal_ensure_schema($pdo);$email=strtolower(trim(isset($data['email'])?(string)$data['email']:''));$name=trim(isset($data['full_name'])?(string)$data['full_name']:'');$type=isset($data['request_type'])?(string)$data['request_type']:'';$allowed=array('access','rectification','update','deletion');if(!filter_var($email,FILTER_VALIDATE_EMAIL)||$name===''||!in_array($type,$allowed,true))throw new RuntimeException('Completá nombre, email y tipo de solicitud.');$public='DAT-'.date('Ymd').'-'.strtoupper(substr(bin2hex(random_bytes(6)),0,10));$st=$pdo->prepare('INSERT INTO privacy_requests(public_id,email,full_name,request_type,details) VALUES(?,?,?,?,?)');$st->execute(array($public,$email,$name,$type,trim(isset($data['details'])?(string)$data['details']:'')));return $public;}
}
if(!function_exists('tickex_legal_privacy_requests')){
 function tickex_legal_privacy_requests($pdo){tickex_legal_ensure_schema($pdo);return $pdo->query('SELECT * FROM privacy_requests ORDER BY id DESC LIMIT 100')->fetchAll(PDO::FETCH_ASSOC);}
}
if(!function_exists('tickex_legal_update_privacy_request')){
 function tickex_legal_update_privacy_request($pdo,$id,$status,$note,$adminId){$allowed=array('received','reviewing','completed','rejected');if(!in_array($status,$allowed,true))throw new RuntimeException('Estado inválido.');$st=$pdo->prepare("UPDATE privacy_requests SET status=:status,resolution_note=:note,updated_at=CURRENT_TIMESTAMP,resolved_at=CASE WHEN :status IN ('completed','rejected') THEN CURRENT_TIMESTAMP ELSE NULL END,resolved_by_admin_id=:admin WHERE id=:id");$st->execute(array(':status'=>$status,':note'=>trim((string)$note),':admin'=>(int)$adminId,':id'=>(int)$id));}
}
